### ISSUE TITLE
Pls meak better kthxbye

### ISSUE THREAD

**Issue by ghost** [codebottle-io/discord-bot#1]

**Comment by MicroDroid** [comment]
Technically the bot is just more like a hacky one, it isn't meant to be a good one.

This is because we're waiting for the new API which will be entirely something else

**Comment by Cat-who-loves-bots** [comment]
ugh new API

**Comment by ghost** [comment]
love that invisible shit whatever it is

**Comment by MicroDroid** [comment]
Well technically you can fork, modify, and PR back any interesting changes, we're so open for that regardless
